# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script: |

    wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20200826/codeql-runner-linux

    chmod +x codeql-runner-linux

  displayName: 'Get latest CodeQL package. Install on Agent.'
- script: |

    ./codeql-runner-linux init \

    --repository pghodki/devsecops-poc \

    --github-url https://github.com \

    --github-auth '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' \

    --config-file .github/codeql/codeql-config.yml 

  displayName: 'Initialize CodeQL Executable and create a CodeQL database'
- script: |

    ./codeql-runner-linux analyze \

    --repository CanarysPlayground/ScanGHfromAzDO \

    --github-url https://github.com \

    --github-auth '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' \

    --commit $(BUILD_SOURCEVERSION) \

    --ref $(Build.SourceBranch)

  displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'